baseURL = "http://linkuprecycling.com/"
languageCode = "en-us"
title = "LinkUP"
theme = "minimal"
publishDir = "docs"

[params]
    author = "Richard Thronton"
    description = "Currently in stealth mode"
    githubUsername = "#"
    accent = "#20c5b4" #rgb(32, 197, 180)
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2
